# Generated by Django 3.2 on 2023-08-05 07:56

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Список покупок',
                'verbose_name_plural': 'Списки покупок',
                'ordering': ('-id',),
                'default_related_name': 'shopping_cart',
            },
        ),
        migrations.CreateModel(
            name='Favorites',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'избранное',
                'ordering': ('-id',),
                'default_related_name': 'favorites',
            },
        ),
        migrations.CreateModel(
            name='Ingridients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='введите название ингридиента', max_length=200, verbose_name='Название ингридиента')),
                ('measurement_unit', models.CharField(help_text='введите меру измерения', max_length=200, verbose_name='единицы измерения')),
            ],
            options={
                'verbose_name': 'Ингредиент',
                'verbose_name_plural': 'Ингредиенты',
                'db_table': 'ingridients',
                'ordering': ('name',),
                'default_related_name': 'ingrodients',
            },
        ),
        migrations.CreateModel(
            name='RecipeIngridient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1, 'укажите хоть какое-то кол-во')], verbose_name='кол-во ')),
            ],
            options={
                'verbose_name': 'Рецепт с ингридиентами',
                'verbose_name_plural': 'Рецепты с ингридиентами',
            },
        ),
        migrations.CreateModel(
            name='Recipes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='введите название рецепта', max_length=200, verbose_name='название рецепта')),
                ('text', models.TextField(verbose_name='описание рецепта')),
                ('cooking_time', models.PositiveSmallIntegerField(help_text='введите время приготовления в минутах', validators=[django.core.validators.MinValueValidator(1, 'укажите хоть какое-то кол-во')], verbose_name='время приготовления (в минутах)')),
                ('image', models.ImageField(help_text='загрузите картинку', upload_to='recipes', verbose_name='картинка')),
                ('ingridients', models.ManyToManyField(help_text='выберите ингридиенты', related_name='recipes', through='recipes.RecipeIngridient', to='recipes.Ingridients')),
            ],
            options={
                'verbose_name': 'Рецепт',
                'verbose_name_plural': 'Рецепты',
                'ordering': ('-id',),
                'default_related_name': 'recipes',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='введите название тэга', max_length=200, unique=True, verbose_name='название тэга')),
                ('slug', models.SlugField(help_text='введите уникальный слаг', max_length=200, unique=True, verbose_name='слаг')),
                ('color', models.CharField(help_text='введите цвет в формате HEX', max_length=7, unique=True, verbose_name='Цвет в HEX')),
            ],
            options={
                'verbose_name': 'Тэг',
                'verbose_name_plural': 'Тэги',
                'ordering': ('name',),
                'default_related_name': 'tags',
            },
        ),
        migrations.CreateModel(
            name='RecipeTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipes.recipes', verbose_name='ингридиент')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipes.tag', verbose_name='тэг')),
            ],
            options={
                'verbose_name': 'тэг рецепта',
                'verbose_name_plural': 'тэги рецепта',
            },
        ),
        migrations.AddField(
            model_name='recipes',
            name='tags',
            field=models.ManyToManyField(help_text='подберите тэги', related_name='recipes', through='recipes.RecipeTag', to='recipes.Tag', verbose_name='Теги рецепта'),
        ),
    ]
