# Generated by Django 3.2 on 2023-08-05 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Ingridients',
            new_name='Ingredients',
        ),
        migrations.RenameField(
            model_name='recipeingridient',
            old_name='ingridient',
            new_name='ingredient',
        ),
        migrations.RemoveField(
            model_name='recipes',
            name='ingridients',
        ),
        migrations.AddField(
            model_name='recipes',
            name='ingredients',
            field=models.ManyToManyField(help_text='выберите ингридиенты', related_name='recipes', through='recipes.RecipeIngridient', to='recipes.Ingredients'),
        ),
    ]
