# Generated by Django 3.2 on 2023-08-05 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_auto_20230805_1339'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipes',
            old_name='user',
            new_name='author',
        ),
    ]
