# Generated by Django 3.2 on 2023-08-06 10:02

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_rename_user_recipes_author'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recipes',
            options={'default_related_name': 'recipes', 'ordering': ('-pub_date',), 'verbose_name': 'Рецепт', 'verbose_name_plural': 'Рецепты'},
        ),
        migrations.AddField(
            model_name='recipes',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 6, 13, 2, 14, 674332), editable=False, verbose_name='Дата публикации'),
        ),
    ]
